# Einsum-Tutorial

Einsum ist eine Funktion in PyTorch/Numpy, die es uns ermöglicht, flexible und komplexe Operationen auf Tensoren durchzuführen. Einsum verwendet dafür eine kompakte Notation, die auf der Einstein-Summenkonvention basiert.
Um das Konzept besser zu verstehen, schauen wir uns einmal ein paar Beispiele an, für die wir einsum verwenden können:

1. Transponierte Matrix

In [ ]:
import torch
# Zunächst erzeugen wir einen 1D-Tensor "a" mithilfe von torch.arange(6). Unser Tensor a hat die Werte [0, 1, 2, 3, 4, 5]
# Mit .reshape formen wir unseren 1D-Tensor in eine Matrix (also einen 2D-Tensor) um.
a = torch.arange(6).reshape(2, 3)
print(f"Unser ursprünglicher Tensor a: \n {a}")

# Jetzt wollen wir einsum verwenden, um unsere Matrix zu transponieren.
# Alles, was wir dazu machen müssen, ist die Indizes des ursprünglichen Tensors zu vertauschen.
# In unserem urprünglichen Tensor haben wir zwei Dimensionen (2,3). Wir wählen entsprechend 2 Indizes i (für die Zeilen) und j (für die Spalten).
# Wir vertauschen die Indizes ij -> ji, haben jetzt also einen Tensor der Form (3,2)
# Note: in der eckigen Klammer steht eine Liste von Tensoren, auf die wir unsere Einsum-Operation anwenden (hier nur ein Tensor a)

b= torch.einsum('ij->ji', [a])
print(f"\nUnser neuer transponierter Tensor b: \n {b}")

Unser ursprünglicher Tensor a: 
 tensor([[0, 1, 2],
        [3, 4, 5]])

Unser neuer transponierter Tensor b: 
 tensor([[0, 3],
        [1, 4],
        [2, 5]])


2. Matrix-Vektor-Multiplikation

In [ ]:
a = torch.arange(6).reshape(3, 2)
print(f"Tensor a: \n {a}")
b = torch.arange(2)
print(f"\nVektor b: \n {b}")
# i und k respräsentieren hier die Zeilen (3) und Spalten (2) unserer Matrix a.
# k repräsentiert die Spalten in unserem Vektor (hier 2)
# und i die resultierenden Zeilen (hier eine)
c = torch.einsum('ik,k->i', [a, b])
print(f"\nMatrix-Vektor-Multiplikation mit einsum: \n {c}")

# selbes kann erreicht werden mit matmul:
d = torch.matmul(a, b)
print(f"\nMatrix-Vektor-Multiplikation mit matmul: \n {d}")

# Was hier konkret passiert:
# c[0] = 0*0 + 1*1 = 1
# c[1] = 2*0 + 3*1 = 3
# c[2] = 4*0 + 5*1 = 5

Tensor a: 
 tensor([[0, 1],
        [2, 3],
        [4, 5]])

Vektor b: 
 tensor([0, 1])

Matrix-Vektor-Multiplikation mit einsum: 
 tensor([1, 3, 5])

Matrix-Vektor-Multiplikation mit matmul: 
 tensor([1, 3, 5])


In [ ]:
c = a.transpose(0,1)
# print(c)
# print(b)
# torch.matmul(c, b)
torch.einsum("ki,k->i", c, b)

tensor([1, 3, 5])

3. Matrix-Matrix-Multiplikation

In [ ]:
a = torch.arange(2).reshape(1, 2)
print(f"Tensor a: \n {a}")
b = torch.arange(3).reshape(1, 3)
print(f"\nTensor b: \n {b}")
print(torch.einsum("ik,ij->kj",a,b))
torch.einsum("ik,pj->kj",a,b)

Tensor a: 
 tensor([[0, 1]])

Tensor b: 
 tensor([[0, 1, 2]])
tensor([[0, 0, 0],
        [0, 1, 2]])


tensor([[0, 0, 0],
        [0, 1, 2]])

In [ ]:
# Zunächst definieren wir auch hier zwei Matrizen
# Unsere Matrix a besitzt 6 Einträge, verteilt auf zwei Zeilen und drei Spalten
a = torch.arange(6).reshape(2, 3)
print(f"Tensor a: \n {a}")

# Unsere Matrix b besitzt 15 Einträge, verteilt auf drei Zeilen und fünf Spalten
b = torch.arange(15).reshape(3, 5)
print(f"\nTensor b: \n {b}")

# Beim Verwenden von einsum haben wir also pro Matrix zwei Indizes (weil unsere Matrizen 2D-Tensoren sind)
# Die Indizes unserer Matrix a heißen hier i und k, wobei i die Zeilen und k die Spalten repräsentiert
# Die Indizes unserer Matrix b heißen hier k und j, wobei k die Zeilen und j die Spalten repräsentiert
# Unser resultierender Tensor ist ebenfalls eine zweidimensionale Matrix mit 2 Zeilen und fünf Spalten.
# Der Tensor übernimmt also die Anzahl der Zeilen unserer Matrix a und die Anzahl der Spalten unserer Matrix b
c = torch.einsum('ik,kj->ij', [a, b])
print(f"\nMatrix-Matrix-Multiplikation mit einsum: \n {c}")

# selbes kann erreicht werden mit matmul:
d = torch.matmul(a, b)
print(f"\nMatrix-Matrix-Multiplikation mit matmul: \n {d}")

4. Skalarprodukt (Dot Product)

In [ ]:
# für Vektoren
a = torch.arange(5)
print(f"Vektor a: \n {a}")
# unser Vektor b soll Zahlen von 2 bis 6 beinhalten, d.h. er hat eine Länge von 5
# Es ist wichtig, dass unsere beiden Vektoren die gleiche Länge haben, damit wir das Skalarprodukt berechnen können
b = torch.arange(2,7)
print(f"\nVektor b: \n {b}")
c = torch.einsum('i,i->', [a, b])
print(f"\nSkalarprodukt: \n {c}")

# für Matrizen
a = torch.arange(6).reshape(2, 3)
print(f"\nMatrix a: \n {a}")
b = torch.arange(6,12).reshape(2, 3)
print(f"\nMatrix b: \n {b}")
c = torch.einsum('ij,ij->', [a, b])
print(f"\nSkalarprodukt: \n {c}")

# Berechnung:
# 1. jedes Element von a wird mit dem entsprechenden Element von b multipliziert
# 2. Ergebnisse werden summiert:

# Elementweise Multiplikation:
# (0 * 6) + (1 * 7) + (2 * 8) = 0 + 7 + 16 = 23 für die erste Zeile.
# (3 * 9) + (4 * 10) + (5 * 11) = 27 + 40 + 55 = 122 für die zweite Zeile.
# Summe der Ergebnisse: 23 + 122 = 145.
# Deshalb ist das Skalarprodukt c gleich 145.

5. Batch-Matrix-Multiplikation

In [ ]:
# Zunächst erzeugen wir zwei Tensoren, die jeweils 2-dimensional sein sollen und eine Batch-size von 3 haben sollen.
a = torch.randn(3,2,5)
print(f"Tensor a: \n {a}")
b = torch.randn(3,5,3)
print(f"\nTensor b: \n {b}")

# i steht für die Batch-size, j und k sind die Dimensionen des ersten Tensors (Matrix a) und k und l sind die Dimensionen des zweiten Tensors (Matrix b)
# unser resultierender Tensor hat ebenfalls die Batch-size i (hier 3) und die Dimensionen i und j (2,3), also zwei Zeilen und drei Spalten
c= torch.einsum('ijk,ikl->ijl', [a, b])
print(f"\nTensor nach Batch-Matrix-Multiplikation: \n {c}")



Tensor a: 
 tensor([[[ 1.1891, -0.0418,  0.7505, -0.0836, -0.8390],
         [-1.3590, -1.3702,  0.6280, -0.6786,  1.0212]],

        [[ 0.8071,  0.7609, -1.7692, -0.9196, -0.4935],
         [ 0.6132,  0.8848, -0.4748, -0.3292,  0.1937]],

        [[-0.0472, -0.1488, -1.1909, -0.0787,  0.6347],
         [ 0.6059,  0.1862,  0.1656,  0.0903, -0.4949]]])

Tensor b: 
 tensor([[[-7.9998e-01, -9.9425e-03, -1.6830e+00],
         [-5.4608e-01,  1.8972e+00,  6.5259e-01],
         [ 8.4350e-01, -1.4574e+00,  2.4578e-01],
         [ 1.5578e+00,  1.5338e+00,  6.8357e-01],
         [-1.5930e+00,  8.5173e-01,  9.0081e-01]],

        [[-7.8388e-01, -1.8298e-01, -4.0267e-01],
         [-3.3046e+00, -2.2277e+00,  7.0962e-01],
         [ 5.9349e-02, -8.5548e-01, -3.0694e-01],
         [ 4.5296e-01,  2.4547e-03, -1.1256e+00],
         [ 1.4081e+00, -4.6863e-01, -1.4826e+00]],

        [[ 5.0620e-01,  1.6719e+00,  1.5378e+00],
         [-1.0125e+00, -7.6826e-01,  8.6710e-02],
         [-2.1543e-01,  8.952

In [ ]:
batch_size, seq_len = 3, 5
A = torch.zeros((batch_size, seq_len))
A[0,0:] = 1
A[1,0:] = 2
A[2,0:] = 3
B = A.unsqueeze(1).expand(-1, batch_size, -1) # (bs, bs!, seq_len)
# mat_mul has many case distinctions. For example, here it ignores the first dimension (batch dimension) and does multiplication on the tensor for each batch, i.e. dimension 1:
# Check with the following code. Use B = A.unsqueeze(1).expand(-1, 4, -1)
A_ = torch.zeros((4, 5))
A_[0,0:] = 1
A_[1,0:] = 2
A_[2,0:] = 3

In [ ]:
print(A.shape)
print(B.shape)
A.view(seq_len, -1)
A.transpose(0,1)

torch.Size([3, 5])
torch.Size([3, 3, 5])


tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [ ]:
# Error:
# torch.matmul(B,A)
#Fix?
torch.matmul(A.view(seq_len, -1),B) # (seq_len, bs) * (bs, 3 seq_len)
# C = A.view(seq_len, -1)

#Soll ergeben:
#tensor([[1., 2., 3.],         tensor([[[1., 1., 1., 1., 1.],
#        [1., 2., 3.],                 [1., 1., 1., 1., 1.],
#        [1., 2., 3.],                 [1., 1., 1., 1., 1.]],
#        [1., 2., 3.],
#        [1., 2., 3.]])   *           [[2., 2., 2., 2., 2.],
#                                      [2., 2., 2., 2., 2.],
#                                      [2., 2., 2., 2., 2.]],
#
#                                     [[3., 3., 3., 3., 3.],
#                                      [3., 3., 3., 3., 3.],
#                                      [3., 3., 3., 3., 3.]]])
#
#                         =
#
# tensor([[[ 6.,  6.,  6.,  6.,  6.],
#          [ 6.,  6.,  6.,  6.,  6.],
#          [ 6.,  6.,  6.,  6.,  6.],
#          [ 6.,  6.,  6.,  6.,  6.],
#          [ 6.,  6.,  6.,  6.,  6.]],

#         [[12., 12., 12., 12., 12.],
#          [12., 12., 12., 12., 12.],
#          [12., 12., 12., 12., 12.],
#          [12., 12., 12., 12., 12.],
#          [12., 12., 12., 12., 12.]],

#         [[18., 18., 18., 18., 18.],
#          [18., 18., 18., 18., 18.],
#          [18., 18., 18., 18., 18.],
#          [18., 18., 18., 18., 18.],
#          [18., 18., 18., 18., 18.]]])

# Wo liegt das Problem?
# Gib eine richitge Implementierung mit einsum() und mit matmul()

tensor([[[ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.],
         [ 6.,  6.,  6.,  6.,  6.],
         [ 8.,  8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.,  9.]],

        [[ 6.,  6.,  6.,  6.,  6.],
         [ 8.,  8.,  8.,  8.,  8.],
         [12., 12., 12., 12., 12.],
         [16., 16., 16., 16., 16.],
         [18., 18., 18., 18., 18.]],

        [[ 9.,  9.,  9.,  9.,  9.],
         [12., 12., 12., 12., 12.],
         [18., 18., 18., 18., 18.],
         [24., 24., 24., 24., 24.],
         [27., 27., 27., 27., 27.]]])