# **Tensors with PyTorch**

In [1]:
# First, install and import the necessary libraries
import torch
import numpy as np
import matplotlib.pyplot as plt
print(f"PyTorch version: {torch.__version__}")

PyTorch version: 2.11.0+cpu


What is a Tensor?

A tensor is a mathematical object that generalizes scalars, vectors, and matrices:
- **Scalar** (0D tensor): A single number
- **Vector** (1D tensor): An array of numbers
- **Matrix** (2D tensor): A 2D array of numbers
- **Tensor** (3D+ tensor): Multi-dimensional arrays

In [2]:
# Scalar (0D tensor)
scalar = torch.tensor(42)
print(f"Scalar: {scalar}")
print(f"Shape: {scalar.shape}")
print(f"Dimensions: {scalar.ndim}")
print()

# Vector (1D tensor)
vector = torch.tensor([1, 2, 3, 4, 5])
print(f"Vector: {vector}")
print(f"Shape: {vector.shape}")
print(f"Dimensions: {vector.ndim}")
print()

# Matrix (2D tensor)
matrix = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"Shape: {matrix.shape}")
print(f"Dimensions: {matrix.ndim}")
print()

# 3D Tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])
print(f"3D Tensor:\n{tensor_3d}")
print(f"Shape: {tensor_3d.shape}")
print(f"Dimensions: {tensor_3d.ndim}")


Scalar: 42
Shape: torch.Size([])
Dimensions: 0

Vector: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Dimensions: 2

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Dimensions: 3


# **Creating Tensors**

In [3]:
# Create tensors with specific values
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 3)
full = torch.full((2, 2), 7)

print("Zeros tensor:")
print(zeros)
print("\nOnes tensor:")
print(ones)
print("\nFull tensor (filled with 7):")
print(full)

Zeros tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Full tensor (filled with 7):
tensor([[7, 7],
        [7, 7]])


In [6]:
# Random tensors
random_uniform = torch.rand(3, 3)  # Uniform distribution [0, 1)
random_normal = torch.randn(3, 3)  # Normal distribution (mean=0, std=1)

In [7]:
print("\nRandom uniform tensor:")
print(random_uniform)
print("\nRandom normal tensor:")
print(random_normal)


Random uniform tensor:
tensor([[0.4138, 0.7786, 0.2995],
        [0.4199, 0.9994, 0.7604],
        [0.8446, 0.6517, 0.2770]])

Random normal tensor:
tensor([[-0.5156, -0.3838, -1.1518],
        [-1.0378, -0.2458, -0.3882],
        [-1.3881,  0.0773,  0.1667]])


In [8]:
# Create tensor from Python list or NumPy array
python_list = [[1, 2, 3], [4, 5, 6]]
tensor_from_list = torch.tensor(python_list)

numpy_array = np.array([[7, 8, 9], [10, 11, 12]])
tensor_from_numpy = torch.from_numpy(numpy_array)

print("\nTensor from Python list:")
print(tensor_from_list)
print("\nTensor from NumPy array:")
print(tensor_from_numpy)


Tensor from Python list:
tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor from NumPy array:
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [9]:
# Create tensors with specific data types
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

print(f"\nFloat tensor: {float_tensor}, dtype: {float_tensor.dtype}")
print(f"Int tensor: {int_tensor}, dtype: {int_tensor.dtype}")



Float tensor: tensor([1., 2., 3.]), dtype: torch.float32
Int tensor: tensor([1, 2, 3]), dtype: torch.int64


# **Tensor properties and indexing**

In [10]:
# Create a sample tensor
sample = torch.randn(3, 4, 5)

print(f"Tensor shape: {sample.shape}")
print(f"Tensor size: {sample.size()}")  # Alternative to shape
print(f"Number of dimensions: {sample.ndim}")
print(f"Total number of elements: {sample.numel()}")
print(f"Data type: {sample.dtype}")
print(f"Device: {sample.device}")

Tensor shape: torch.Size([3, 4, 5])
Tensor size: torch.Size([3, 4, 5])
Number of dimensions: 3
Total number of elements: 60
Data type: torch.float32
Device: cpu


In [11]:
# Indexing and slicing
matrix = torch.tensor([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])

print("\nOriginal matrix:")
print(matrix)

# Access specific elements
print(f"\nElement at [0, 1]: {matrix[0, 1]}")
print(f"Element at [2, 3]: {matrix[2, 3]}")

# Slicing
print(f"\nFirst row: {matrix[0, :]}")
print(f"Second column: {matrix[:, 1]}")
print(f"Submatrix [0:2, 1:3]:\n{matrix[0:2, 1:3]}")



Original matrix:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Element at [0, 1]: 2
Element at [2, 3]: 12

First row: tensor([1, 2, 3, 4])
Second column: tensor([ 2,  6, 10])
Submatrix [0:2, 1:3]:
tensor([[2, 3],
        [6, 7]])


# **Tensor operations**

In [ ]:
# Basic arithmetic operations
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print("Tensor a:")
print(a)
print("\nTensor b:")
print(b)

# Element-wise operations
print(f"\nAddition (a + b):\n{a + b}")
print(f"\nSubtraction (a - b):\n{a - b}")
print(f"\nElement-wise multiplication (a * b):\n{a * b}")
print(f"\nElement-wise division (a / b):\n{a / b}")

# Matrix multiplication
print(f"\nMatrix multiplication (a @ b):\n{a @ b}")
print(f"\nAlternative matrix multiplication:\n{torch.matmul(a, b)}")

# Other useful operations
x = torch.tensor([1.0, 4.0, 9.0, 16.0])
print(f"\nOriginal tensor: {x}")
print(f"Square root: {torch.sqrt(x)}")
print(f"Exponential: {torch.exp(x)}")
print(f"Logarithm: {torch.log(x)}")

Tensor a:
tensor([[1., 2.],
        [3., 4.]])

Tensor b:
tensor([[5., 6.],
        [7., 8.]])

Addition (a + b):
tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction (a - b):
tensor([[-4., -4.],
        [-4., -4.]])

Element-wise multiplication (a * b):
tensor([[ 5., 12.],
        [21., 32.]])

Element-wise division (a / b):
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Matrix multiplication (a @ b):
tensor([[19., 22.],
        [43., 50.]])

Alternative matrix multiplication:
tensor([[19., 22.],
        [43., 50.]])

Original tensor: tensor([ 1.,  4.,  9., 16.])
Square root: tensor([1., 2., 3., 4.])
Exponential: tensor([2.7183e+00, 5.4598e+01, 8.1031e+03, 8.8861e+06])
Logarithm: tensor([0.0000, 1.3863, 2.1972, 2.7726])


# **Tensor reshaping and manipulation**

In [ ]:
# Create a sample tensor
original = torch.arange(12)
print(f"Original tensor: {original}")
print(f"Shape: {original.shape}")

# Reshape operations
reshaped_2d = original.reshape(3, 4)
reshaped_3d = original.reshape(2, 2, 3)

print(f"\nReshaped to 3x4:\n{reshaped_2d}")
print(f"\nReshaped to 2x2x3:\n{reshaped_3d}")

# View vs reshape (view requires contiguous memory)
viewed = original.view(4, 3)
print(f"\nViewed as 4x3:\n{viewed}")

# Transpose operations
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nOriginal matrix:\n{matrix}")
print(f"Transposed:\n{matrix.T}")
print(f"Transpose using .transpose():\n{matrix.transpose(0, 1)}")

# Squeeze and unsqueeze (remove/add dimensions of size 1)
tensor_with_extra_dim = torch.randn(1, 3, 1, 4)
print(f"\nTensor with extra dimensions: {tensor_with_extra_dim.shape}")
squeezed = tensor_with_extra_dim.squeeze()
print(f"After squeezing: {squeezed.shape}")

unsqueezed = squeezed.unsqueeze(0).unsqueeze(2)
print(f"After unsqueezing: {unsqueezed.shape}")


Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])

Reshaped to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped to 2x2x3:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

Viewed as 4x3:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Transposed:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Transpose using .transpose():
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Tensor with extra dimensions: torch.Size([1, 3, 1, 4])
After squeezing: torch.Size([3, 4])
After unsqueezing: torch.Size([1, 3, 1, 4])


# **Broadcasting**
allows operations between tensors of different shapes

In [ ]:
# Broadcasting examples
a = torch.tensor([[1, 2, 3]])  # Shape: (1, 3)
b = torch.tensor([[4], [5], [6]])  # Shape: (3, 1)

print("Tensor a (1x3):")
print(a)
print("\nTensor b (3x1):")
print(b)

# Broadcasting multiplication
result = a * b  # Results in (3, 3) tensor
print(f"\nBroadcasted multiplication result (3x3):\n{result}")

# More broadcasting examples
scalar = torch.tensor(2)
vector = torch.tensor([1, 2, 3, 4])
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(f"\nScalar + Vector: {scalar + vector}")
print(f"Matrix + Scalar:\n{matrix + scalar}")

Tensor a (1x3):
tensor([[1, 2, 3]])

Tensor b (3x1):
tensor([[4],
        [5],
        [6]])

Broadcasted multiplication result (3x3):
tensor([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]])

Scalar + Vector: tensor([3, 4, 5, 6])
Matrix + Scalar:
tensor([[3, 4],
        [5, 6],
        [7, 8]])


# **Reduction operations**
reduce tensor dimensions

In [ ]:
data = torch.tensor([[1.0, 2.0, 3.0],
                    [4.0, 5.0, 6.0],
                    [7.0, 8.0, 9.0]])

print("Original data:")
print(data)

# Various reduction operations
print(f"\nSum of all elements: {torch.sum(data)}")
print(f"Mean of all elements: {torch.mean(data)}")
print(f"Max value: {torch.max(data)}")
print(f"Min value: {torch.min(data)}")

# Reductions along specific dimensions
print(f"\nSum along rows (dim=0): {torch.sum(data, dim=0)}")
print(f"Sum along columns (dim=1): {torch.sum(data, dim=1)}")
print(f"Mean along rows (dim=0): {torch.mean(data, dim=0)}")
print(f"Mean along columns (dim=1): {torch.mean(data, dim=1)}")

Original data:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Sum of all elements: 45.0
Mean of all elements: 5.0
Max value: 9.0
Min value: 1.0

Sum along rows (dim=0): tensor([12., 15., 18.])
Sum along columns (dim=1): tensor([ 6., 15., 24.])
Mean along rows (dim=0): tensor([4., 5., 6.])
Mean along columns (dim=1): tensor([2., 5., 8.])


# **Practical example: Image as a tensor**

In [12]:
# Create a simple "image" (3 channels, 4x4 pixels)
# In practice, images are often (Channels, Height, Width) or (Height, Width, Channels)
image_tensor = torch.randint(0, 256, (3, 4, 4), dtype=torch.uint8)

print(f"Image tensor shape: {image_tensor.shape}")
print(f"Red channel (channel 0):\n{image_tensor[0]}")
print(f"Green channel (channel 1):\n{image_tensor[1]}")
print(f"Blue channel (channel 2):\n{image_tensor[2]}")

# Convert to float and normalize (common preprocessing step)
normalized_image = image_tensor.float() / 255.0
print(f"\nNormalized image (first channel):\n{normalized_image[0]}")

# Reshape for different formats
# From CHW (Channel, Height, Width) to HWC (Height, Width, Channel)
hwc_format = image_tensor.permute(1, 2, 0)
print(f"\nReshaped to HWC format: {hwc_format.shape}")


Image tensor shape: torch.Size([3, 4, 4])
Red channel (channel 0):
tensor([[170,  22,   5,  16],
        [  0,  19, 209, 200],
        [ 78, 248, 149, 142],
        [118, 245, 250, 105]], dtype=torch.uint8)
Green channel (channel 1):
tensor([[183, 200, 119, 109],
        [ 92, 155,  99,  59],
        [134, 195, 229, 234],
        [ 34,  85,  26, 199]], dtype=torch.uint8)
Blue channel (channel 2):
tensor([[193, 240, 245, 121],
        [100, 226,   9,   1],
        [213, 230, 236, 207],
        [ 97,  98,  77,   6]], dtype=torch.uint8)

Normalized image (first channel):
tensor([[0.6667, 0.0863, 0.0196, 0.0627],
        [0.0000, 0.0745, 0.8196, 0.7843],
        [0.3059, 0.9725, 0.5843, 0.5569],
        [0.4627, 0.9608, 0.9804, 0.4118]])

Reshaped to HWC format: torch.Size([4, 4, 3])


# **NLP application: Representing sentences as tensors**

In [13]:
# Example sentence for supertagging
sentence = "The cat sat on the mat"
words = sentence.split()
print(f"Original sentence: '{sentence}'")
print(f"Tokenized words: {words}")

# Create a simple vocabulary (in practice, you'd have a much larger vocabulary)
vocab = {
    '<PAD>': 0,   # Padding token
    '<UNK>': 1,   # Unknown token
    'the': 2,
    'cat': 3,
    'sat': 4,
    'on': 5,
    'mat': 6,
    'dog': 7,
    'ran': 8,
    'under': 9,
    'table': 10
}

# Convert words to indices (token IDs)
def words_to_indices(words, vocab):
    return [vocab.get(word.lower(), vocab['<UNK>']) for word in words]

token_ids = words_to_indices(words, vocab)
print(f"Token IDs: {token_ids}")

# Convert to tensor
sentence_tensor = torch.tensor(token_ids, dtype=torch.long)
print(f"Sentence as tensor: {sentence_tensor}")
print(f"Tensor shape: {sentence_tensor.shape}")

Original sentence: 'The cat sat on the mat'
Tokenized words: ['The', 'cat', 'sat', 'on', 'the', 'mat']
Token IDs: [2, 3, 4, 5, 2, 6]
Sentence as tensor: tensor([2, 3, 4, 5, 2, 6])
Tensor shape: torch.Size([6])


In practice, we process multiple sentences at once:

In [14]:
# Multiple sentences of different lengths
sentences = [
    "The cat sat on the mat",
    "The dog ran under the table",
    "The cat ran"
]

# Tokenize all sentences
all_tokens = [sentence.split() for sentence in sentences]
print("All tokenized sentences:")
for i, tokens in enumerate(all_tokens):
    print(f"  Sentence {i+1}: {tokens}")

# Convert to token IDs
all_token_ids = [words_to_indices(tokens, vocab) for tokens in all_tokens]
print(f"\nAll token IDs: {all_token_ids}")

# Pad sequences to same length (required for batching)
max_length = max(len(seq) for seq in all_token_ids)
print(f"Maximum sequence length: {max_length}")

def pad_sequence(sequences, max_len, pad_token=0):
    padded = []
    for seq in sequences:
        if len(seq) < max_len:
            # Pad with pad_token
            padded_seq = seq + [pad_token] * (max_len - len(seq))
        else:
            # Truncate if too long
            padded_seq = seq[:max_len]
        padded.append(padded_seq)
    return padded

padded_sequences = pad_sequence(all_token_ids, max_length)
print(f"Padded sequences: {padded_sequences}")

# Create batch tensor
batch_tensor = torch.tensor(padded_sequences, dtype=torch.long)
print(f"\nBatch tensor shape: {batch_tensor.shape}")  # (batch_size, sequence_length)
print(f"Batch tensor:\n{batch_tensor}")

All tokenized sentences:
  Sentence 1: ['The', 'cat', 'sat', 'on', 'the', 'mat']
  Sentence 2: ['The', 'dog', 'ran', 'under', 'the', 'table']
  Sentence 3: ['The', 'cat', 'ran']

All token IDs: [[2, 3, 4, 5, 2, 6], [2, 7, 8, 9, 2, 10], [2, 3, 8]]
Maximum sequence length: 6
Padded sequences: [[2, 3, 4, 5, 2, 6], [2, 7, 8, 9, 2, 10], [2, 3, 8, 0, 0, 0]]

Batch tensor shape: torch.Size([3, 6])
Batch tensor:
tensor([[ 2,  3,  4,  5,  2,  6],
        [ 2,  7,  8,  9,  2, 10],
        [ 2,  3,  8,  0,  0,  0]])


# **Word embeddings: From tokens to vectors**

In [15]:
# Create simple word embeddings
vocab_size = len(vocab)
embedding_dim = 50  # Each word represented as 50-dimensional vector

# Initialize embedding layer (this is what neural networks learn)
embedding_layer = torch.nn.Embedding(vocab_size, embedding_dim)

# Convert our batch of token IDs to embeddings
word_embeddings = embedding_layer(batch_tensor)
print(f"\nWord embeddings shape: {word_embeddings.shape}")  # (batch_size, seq_len, embedding_dim)
print(f"First word embedding (first sentence, first word):\n{word_embeddings[0, 0, :10]}")  # Show first 10 dims




Word embeddings shape: torch.Size([3, 6, 50])
First word embedding (first sentence, first word):
tensor([-0.3293,  0.2274, -0.7025,  0.6847, -2.5519,  1.9139, -0.8007, -2.3687,
         0.9398, -1.6082], grad_fn=<SliceBackward0>)


Supertagging context: POS tags and supertags as tensors

In [16]:
# Example: Part-of-speech tags for our sentences
pos_tags = [
    ["DT", "NN", "VBD", "IN", "DT", "NN"],      # The cat sat on the mat
    ["DT", "NN", "VBD", "IN", "DT", "NN"],      # The dog ran under the table
    ["DT", "NN", "VBD", "<PAD>", "<PAD>", "<PAD>"]  # The cat ran (padded)
]

# Create POS tag vocabulary
pos_vocab = {
    '<PAD>': 0,
    'DT': 1,    # Determiner
    'NN': 2,    # Noun
    'VBD': 3,   # Past tense verb
    'IN': 4,    # Preposition
}

# Convert POS tags to indices
pos_indices = []
for tags in pos_tags:
    indices = [pos_vocab.get(tag, 0) for tag in tags]
    pos_indices.append(indices)

pos_tensor = torch.tensor(pos_indices, dtype=torch.long)
print(f"POS tags as tensor:\n{pos_tensor}")

# Example: Supertags (simplified CCG-style)
# In real supertagging, these would be complex syntactic categories
supertags = [
    ["NP/N", "N", "S\\NP", "(S\\NP)/NP", "NP/N", "N"],
    ["NP/N", "N", "S\\NP", "(S\\NP)/NP", "NP/N", "N"],
    ["NP/N", "N", "S\\NP", "<PAD>", "<PAD>", "<PAD>"]
]

# Create supertag vocabulary (simplified)
supertag_vocab = {
    '<PAD>': 0,
    'N': 1,           # Noun
    'NP/N': 2,        # Determiner (NP seeking N to the right)
    'S\\NP': 3,       # Intransitive verb (S seeking NP to the left)
    '(S\\NP)/NP': 4,  # Transitive verb (S seeking NP left and right)
}

supertag_indices = []
for tags in supertags:
    indices = [supertag_vocab.get(tag, 0) for tag in tags]
    supertag_indices.append(indices)

supertag_tensor = torch.tensor(supertag_indices, dtype=torch.long)
print(f"Supertags as tensor:\n{supertag_tensor}")

POS tags as tensor:
tensor([[1, 2, 3, 4, 1, 2],
        [1, 2, 3, 4, 1, 2],
        [1, 2, 3, 0, 0, 0]])
Supertags as tensor:
tensor([[2, 1, 3, 4, 2, 1],
        [2, 1, 3, 4, 2, 1],
        [2, 1, 3, 0, 0, 0]])
